site_name: hammerMC
copyright: Copyright &copy; 2023 - 2024 hamium
repo_url: https://github.com/hamium/hammer-docs
repo_name: hamium/hammer-docs
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Commands: commands.md
  - Config:
      Global variables: config/variables.md
theme:
  name: material
  logo: assets/imgs/logo_no_border.png
  favicon: assets/imgs/logo.png
  font:
    text: Inter
  icon:
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
    view: material/eye
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: custom
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: custom
  features:
    - content.tooltips
    - content.tabs.link
    - navigation.top
    - navigation.sections
    - navigation.indexes
    - navigation.path
    - header.autohide
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - content.action.edit

extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hamium

extra_css:
  - assets/stylesheets/colors.css

markdown_extensions:
  - pymdownx.blocks.tab
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
  - glightbox : 
      touchNavigation: true
      effect: zoom
      slide_effect: slide
  - git-committers:
      repository: hamium/smp-wiki
      branch: main
  - git-revision-date-localized:
      enable_creation_date: false
      enabled: true
